development:
  REACT_APP_FRESHDESK_BASE_URL: "https://test8653.freshdesk.com/api/v2"
  REACT_APP_FRESHDESK_API_KEY: "rDk2JZ9i5HvQbGu2GX36"

production:
  REACT_APP_FRESHDESK_BASE_URL: "https://test8653.freshdesk.com/api/v2"
  REACT_APP_FRESHDESK_API_KEY: "rDk2JZ9i5HvQbGu2GX36"

test:
  REACT_APP_FRESHDESK_BASE_URL: "https://test8653.freshdesk.com/api/v2"
  REACT_APP_FRESHDESK_API_KEY: "rDk2JZ9i5HvQbGu2GX36"
